# Generated by Django 4.1.7 on 2023-04-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.IntegerField(choices=[(1, 'restaurant'), (2, 'cafe'), (3, 'bar')])),
                ('address', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('city', models.CharField(default='Minsk', max_length=100)),
            ],
        ),
    ]
