# Generated by Django 4.1.7 on 2023-05-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=100)),
                ('hobby_category', models.CharField(choices=[('art', 'Art'), ('spo', 'Sport'), ('act', 'Active rest'), ('cre', 'Creactivity'), ('oth', 'Others')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_address', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.cities')),
                ('supported_hobbies', models.ManyToManyField(to='arrangement.hobbies')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.PositiveIntegerField()),
                ('feedback_about_user', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(to='arrangement.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Establishments',
        ),
        migrations.AddField(
            model_name='placerating',
            name='place_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.places'),
        ),
        migrations.AddField(
            model_name='placerating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrangement.users'),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='place',
            field=models.ManyToManyField(blank=True, to='arrangement.places'),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='user',
            field=models.ManyToManyField(to='arrangement.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='hobby',
            field=models.ManyToManyField(to='arrangement.hobbies'),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrangement.cities'),
        ),
    ]
